version: '3'

services:
    razor-components:
        image: mewgrammer/cloudinabox:latest
        restart: always
        ports:
            - 443:443
            - 80:80
        networks:
            - mainNet
networks:
    mainNet:
        driver: bridge
